In [3]:
import numpy as np
import pandas as pd
import math
import pingouin as pg

In [4]:
# Read in the BFI Acoustics data

bfia_df = pd.read_csv('BFI_Acoustics.csv', sep=',', header=0, index_col=0)
bfia_df

Loud  Heavy Bass  Brass  Woodwind  Dense  Fast   Percussive   \
S.No                                                                 
1        3           5      5         3      3      4            5   
2        4           5      3         3      3      4            3   
3        2           3      3         5      2      4            4   
4        3           5      3         1      4      4            4   
5        2           2      4         4      3      4            4   
6        3           5      3         3      3      3            4   
7        3           4      4         3      4      3            3   
8        1           1      2         1      1      3            2   
9        3           3      3         3      3      3            4   
10       3           3      3         3      2      4            4   
11       3           3      3         3      4      4            3   
12       3           3      2         3      2      4            4   
13       4           4      3         3      3      4            5   
14       4           4      3         3      5      4            5   
15       4           2      2         3      3      4            5   
16       3           4      3         2      4      4            4   
17       3           4      3         4      4      3            2   
18       1           2      4         4      4      2            4   
19       3           3      3         2      4      4            3   
20       4           5      2         2      4      3            2   
21       2           1      4         4      3      4            4   
22       5           5      3         1      4      4            3   
23       1           1      1         5      3      3            4   
24       4           4      3         3      3      3            3   
25       5           2      2         4      5      5            2   
26       4           3      4         4      4      4            3   
27       3           3      3         3      3      4            5   
28       3           3      4         5      3      4            4   
29       4           5      4         5      3      5            4   
30       2           1      2         2      4      3            2   
31       3           3      2         2      2      4            5   

      Raspy voice   Piano   Distorted   ...  Synthesizer  Electric  \
S.No                                    ...                          
1                5       3           5  ...            4         4   
2                2       4           3  ...            3         4   
3                4       4           1  ...            3         3   
4                1       3           1  ...            4         4   
5                2       4           2  ...            3         4   
6                2       4           4  ...            4         4   
7                2       3           3  ...            4         4   
8                2       5           3  ...            3         3   
9                2       4           4  ...            4         3   
10               1       4           2  ...            5         5   
11               3       3           1  ...            3         3   
12               2       4           4  ...            4         4   
13               3       3           5  ...            3         3   
14               4       4           4  ...            3         4   
15               5       4           1  ...            2         3   
16               2       5           3  ...            4         4   
17               2       5           2  ...            3         3   
18               4       5           3  ...            4         4   
19               4       3           3  ...            2         4   
20               5       5           3  ...            5         5   
21               4       5           2  ...            3         2   
22               4       1           5  ...            4         3   
23             

In [5]:
# Read in the BFI Personality data

bfip_df = pd.read_csv('BFI_Personality.csv', sep=',', header=0, index_col=0)
bfip_df

I am the life of the party  I feel little concern for others  \
S.No                                                                 
1                              1                                 1   
2                              4                                 2   
3                              1                                 4   
4                              2                                 4   
5                              4                                 2   
6                              4                                 5   
7                              2                                 1   
8                              1                                 1   
9                              1                                 2   
10                             3                                 1   
11                             1                                 1   
12                             2                                 2   
13                             1                                 1   
14                             2                                 1   
15                             2                                 2   
16                             2                                 3   
17                             2                                 2   
18                             3                                 3   
19                             4                                 3   
20                             4                                 2   
21                             4                                 5   
22                             4                                 1   
23                             1                                 1   
24                             3                                 2   
25                             4                                 4   
26                             3                                 2   
27                             3                                 2   
28                             3                                 4   
29                             2                                 1   
30                             2                                 4   
31                             4                                 2   

      I leave my belongings around  I am relaxed most of the time  \
S.No                                                                
1                                1                              4   
2                                4                              2   
3                                2                              3   
4                                1                              5   
5                                4                              3   
6                                5                              2   
7                                2                              2   
8                                3                              5   
9                                3                              2   
10                               2                              5   
11                               1                              2   
12                               5                              3   
13                               2                              3   
14                               3                              4   
15                               5                              1   
16                               2                              3   
17                               2                              2   
18                               1                              4   
19                               4                              3   
20                               1                              2   
21                               2                              1   
22                               1                              2   
23                               1     

In [6]:
# Reverse Keying 

Personality_Arr = bfip_df.to_numpy()
Personality_Arr

array([[1, 1, 1, 4, 4, 4, 4, 3, 5, 1, 1, 2, 4, 5, 5, 5, 4, 5, 4, 1],
       [4, 2, 4, 2, 2, 2, 4, 2, 4, 3, 5, 2, 4, 3, 3, 3, 4, 4, 3, 1],
       [1, 4, 2, 3, 4, 4, 2, 1, 4, 2, 1, 4, 3, 2, 3, 4, 2, 1, 1, 2],
       [2, 4, 1, 5, 5, 5, 5, 2, 4, 1, 1, 3, 2, 4, 5, 4, 5, 2, 5, 1],
       [4, 2, 4, 3, 3, 2, 5, 3, 3, 3, 2, 1, 5, 3, 4, 2, 5, 1, 3, 1],
       [4, 5, 5, 2, 3, 2, 5, 2, 5, 3, 5, 1, 5, 1, 5, 2, 5, 2, 5, 2],
       [2, 1, 2, 2, 5, 4, 5, 4, 4, 1, 1, 1, 3, 1, 4, 5, 4, 3, 4, 1],
       [1, 1, 3, 5, 5, 5, 5, 2, 1, 3, 1, 2, 1, 5, 2, 5, 5, 1, 1, 2],
       [1, 2, 3, 2, 3, 4, 4, 2, 5, 3, 2, 4, 4, 2, 3, 4, 4, 3, 2, 2],
       [3, 1, 2, 5, 5, 2, 5, 1, 4, 3, 2, 3, 2, 2, 2, 4, 2, 1, 1, 1],
       [1, 1, 1, 2, 2, 4, 5, 3, 5, 1, 3, 1, 2, 2, 4, 3, 4, 1, 3, 1],
       [2, 2, 5, 3, 2, 3, 5, 1, 4, 2, 2, 2, 5, 3, 3, 3, 2, 1, 2, 2],
       [1, 1, 2, 3, 4, 4, 4, 2, 4, 3, 1, 2, 2, 3, 2, 5, 3, 2, 2, 4],
       [2, 1, 3, 4, 4, 3, 5, 1, 4, 4, 3, 1, 4, 3, 4, 3, 5, 2, 2, 4],
       [2, 2, 5, 1, 4, 3, 4, 2, 5,

In [7]:
neg_cols = np.array([1,2,5,8,9,11,12,18,19])

for col in neg_cols:
    Personality_Arr[:,col] = 6 - Personality_Arr[:,col]

Personality_Arr

array([[1, 5, 5, 4, 4, 2, 4, 3, 1, 5, 1, 4, 2, 5, 5, 5, 4, 5, 2, 5],
       [4, 4, 2, 2, 2, 4, 4, 2, 2, 3, 5, 4, 2, 3, 3, 3, 4, 4, 3, 5],
       [1, 2, 4, 3, 4, 2, 2, 1, 2, 4, 1, 2, 3, 2, 3, 4, 2, 1, 5, 4],
       [2, 2, 5, 5, 5, 1, 5, 2, 2, 5, 1, 3, 4, 4, 5, 4, 5, 2, 1, 5],
       [4, 4, 2, 3, 3, 4, 5, 3, 3, 3, 2, 5, 1, 3, 4, 2, 5, 1, 3, 5],
       [4, 1, 1, 2, 3, 4, 5, 2, 1, 3, 5, 5, 1, 1, 5, 2, 5, 2, 1, 4],
       [2, 5, 4, 2, 5, 2, 5, 4, 2, 5, 1, 5, 3, 1, 4, 5, 4, 3, 2, 5],
       [1, 5, 3, 5, 5, 1, 5, 2, 5, 3, 1, 4, 5, 5, 2, 5, 5, 1, 5, 4],
       [1, 4, 3, 2, 3, 2, 4, 2, 1, 3, 2, 2, 2, 2, 3, 4, 4, 3, 4, 4],
       [3, 5, 4, 5, 5, 4, 5, 1, 2, 3, 2, 3, 4, 2, 2, 4, 2, 1, 5, 5],
       [1, 5, 5, 2, 2, 2, 5, 3, 1, 5, 3, 5, 4, 2, 4, 3, 4, 1, 3, 5],
       [2, 4, 1, 3, 2, 3, 5, 1, 2, 4, 2, 4, 1, 3, 3, 3, 2, 1, 4, 4],
       [1, 5, 4, 3, 4, 2, 4, 2, 2, 3, 1, 4, 4, 3, 2, 5, 3, 2, 4, 2],
       [2, 5, 3, 4, 4, 3, 5, 1, 2, 2, 3, 5, 2, 3, 4, 3, 5, 2, 4, 2],
       [2, 4, 1, 1, 4, 3, 4, 2, 1,

In [8]:
Acoustics_Arr = bfia_df.to_numpy()
Acoustics_Arr

array([[3, 5, 5, 3, 3, 4, 5, 5, 3, 5, 4, 5, 4, 4, 4, 4, 4, 5, 5, 3, 5, 2],
       [4, 5, 3, 3, 3, 4, 3, 2, 4, 3, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 3, 3, 5, 2, 4, 4, 4, 4, 1, 1, 4, 3, 3, 2, 2, 2, 2, 2, 2, 2, 1],
       [3, 5, 3, 1, 4, 4, 4, 1, 3, 1, 1, 4, 4, 4, 5, 5, 5, 4, 1, 1, 1, 2],
       [2, 2, 4, 4, 3, 4, 4, 2, 4, 2, 1, 5, 3, 4, 1, 4, 5, 5, 3, 4, 4, 2],
       [3, 5, 3, 3, 3, 3, 4, 2, 4, 4, 2, 3, 4, 4, 3, 4, 2, 4, 3, 3, 5, 2],
       [3, 4, 4, 3, 4, 3, 3, 2, 3, 3, 2, 2, 4, 4, 3, 4, 3, 2, 4, 3, 4, 2],
       [1, 1, 2, 1, 1, 3, 2, 2, 5, 3, 1, 5, 3, 3, 1, 2, 4, 4, 5, 4, 4, 1],
       [3, 3, 3, 3, 3, 3, 4, 2, 4, 4, 3, 5, 4, 3, 4, 4, 3, 4, 4, 4, 4, 1],
       [3, 3, 3, 3, 2, 4, 4, 1, 4, 2, 4, 5, 5, 5, 3, 3, 4, 3, 4, 4, 5, 1],
       [3, 3, 3, 3, 4, 4, 3, 3, 3, 1, 1, 3, 3, 3, 1, 4, 3, 4, 5, 3, 5, 4],
       [3, 3, 2, 3, 2, 4, 4, 2, 4, 4, 1, 4, 4, 4, 3, 3, 3, 3, 5, 5, 4, 4],
       [4, 4, 3, 3, 3, 4, 5, 3, 3, 5, 4, 5, 3, 3, 5, 3, 3, 3, 2, 1, 2, 1],
       [4, 4, 3, 3, 5, 4,

In [9]:
# Score Matrix

Psych_score_mat = np.zeros((Personality_Arr.shape[0], 5))
for i in range(Personality_Arr.shape[0]):
    # Openness
    Psych_score_mat[i,0] = Personality_Arr[i,19] + Personality_Arr[i,14] + Personality_Arr[i,4] + Personality_Arr[i,9]
    
    # Conscientiousness
    Psych_score_mat[i,1] = Personality_Arr[i,7] + Personality_Arr[i,2] + Personality_Arr[i,12] + Personality_Arr[i,17]
    
    # Extraversion
    Psych_score_mat[i,2] = Personality_Arr[i,15] + Personality_Arr[i,0] + Personality_Arr[i,5] + Personality_Arr[i,10]
    
    # Agreeableness
    Psych_score_mat[i,3] = Personality_Arr[i,1] + Personality_Arr[i,11] + Personality_Arr[i,6] + Personality_Arr[i,16]
    
    # Neuroticism
    Psych_score_mat[i,4] = Personality_Arr[i,18] + Personality_Arr[i,8] + Personality_Arr[i,13] + Personality_Arr[i,3]
    
Psych_score_mat = Psych_score_mat / 4
Psych_score_mat

array([[4.75, 3.75, 2.25, 4.25, 3.  ],
       [3.25, 2.5 , 4.  , 4.  , 2.5 ],
       [3.75, 2.25, 2.  , 2.  , 3.  ],
       [5.  , 3.25, 2.  , 3.75, 3.  ],
       [3.75, 1.75, 3.  , 4.75, 3.  ],
       [3.75, 1.5 , 3.75, 4.  , 1.25],
       [4.75, 3.5 , 2.5 , 4.75, 1.75],
       [3.5 , 2.75, 2.  , 4.75, 5.  ],
       [3.25, 2.5 , 2.25, 3.5 , 2.25],
       [3.75, 2.5 , 3.25, 3.75, 3.5 ],
       [4.  , 3.25, 2.25, 4.75, 2.  ],
       [3.25, 1.  , 2.5 , 3.75, 3.  ],
       [2.75, 3.  , 2.25, 4.  , 3.  ],
       [3.  , 2.  , 2.75, 5.  , 3.25],
       [4.  , 1.5 , 2.75, 3.75, 2.  ],
       [3.75, 2.75, 2.75, 3.25, 3.  ],
       [3.75, 4.75, 3.  , 3.5 , 2.75],
       [3.25, 3.5 , 3.25, 3.25, 3.  ],
       [3.25, 2.5 , 3.5 , 3.25, 3.25],
       [4.  , 3.25, 3.25, 3.75, 2.25],
       [3.25, 4.25, 3.5 , 3.  , 1.5 ],
       [4.5 , 3.  , 3.5 , 3.75, 2.25],
       [4.5 , 4.  , 2.25, 3.  , 4.  ],
       [4.  , 3.  , 3.25, 4.  , 4.  ],
       [2.25, 2.5 , 3.5 , 2.5 , 2.25],
       [3.25, 3.75, 3.  ,

In [15]:
Psych_df = pd.DataFrame(Psych_score_mat, columns=['Openness', 'Conscientiousness', 'Extraversion', 'Agreeableness', 'Neuroticism'])
Psych_df
Psych_df.to_csv('Psych_Scores.csv')

In [14]:
pg.cronbach_alpha(data=Psych_df[['Openness']])

AssertionError: At least two items are required.